# Generated by Django 4.0.5 on 2024-05-21 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('medical_image', models.ImageField(upload_to='medical_images/')),
                ('type', models.CharField(default='No Type', max_length=100)),
                ('result', models.CharField(default='No result', max_length=100)),
            ],
        ),
    ]
